name: Build
on:
  push:
    tags:
      - 'v[0-9]+.*'

defaults:
  run:
    shell: bash

jobs:
  version:
    name: Check Version
    runs-on: ubuntu-latest
    #runs-on: [ self-hosted, Linux ]
    outputs:
      long: ${{ steps.good.outputs.long }}
      short: ${{ steps.good.outputs.short }}
      linuxName: libLLVM-${{ steps.good.outputs.short }}.so
      macName: libLLVM-${{ steps.good.outputs.short }}.dylib
      winName: LLVM-${{ steps.good.outputs.short }}.dll
    steps:
      - name: Good Version
        id: good
        if: |
            github.ref_type == 'tag' &&
            startsWith(github.ref_name, 'v')
        run: |
          if [[ ${version:1:2} =~ ^-?[0-9]+$ ]]; then
            echo "::set-output name=long::${version:1}"
            echo "::set-output name=short::${version:1:2}"
          else
            echo "LLVM version ${version:1:2}, derived from -- $version -- is not numeric."
            exit 1
          fi
        env:
          version: ${{ github.ref_name }}
      - name: Bad Version
        id: bad
        if: |
            github.ref_type != 'tag' ||
            !startsWith(github.ref_name, 'v')
        run: |
          echo "The build script expects tag to be in the format v14.0.6"
          exit 1

  build:
    name: Build LLVM
    runs-on: ${{ matrix.os }}
    #runs-on: ${{ matrix.sh }}
    strategy:
      matrix:
          include:
          - os: ubuntu-22.04
            sh: [ self-hosted, Linux ]
            finalName:  ${{ needs.version.outputs.linuxName }}
            builtAs: llvm/build/_install/lib/libLLVM-${{ needs.version.outputs.short }}.so
          - os: macos-12
            sh: [ self-hosted, macos ]
            finalName:  ${{ needs.version.outputs.macName }}
            builtAs: llvm/build/_install/lib/libLLVM.dylib
          - os: windows-2022
            sh: [ self-hosted, windows ]
            finalName:  ${{ needs.version.outputs.winName }}
            builtAs: llvm/build/_install/bin/LLVM-C.dll
      fail-fast: false
    needs: version
    env: 
      workingDir: llvm/build
      builtDir: llvm/build/_install
      finalDir: libLLVM-${{ needs.version.outputs.short }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout LLVM
        uses: actions/checkout@v3
        with:
          repository: 'llvm/llvm-project'
          ref: 'release/${{ needs.version.outputs.short }}.x'
      - name: Setup MS Build
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v1.1
      - name: Install Dependencies
        run: |
          case "${RUNNER_OS}" in
              Linux)    sudo apt install ninja-build ;;
              macOS)    brew install ninja ;;
              Windows)  echo "No Ninja requirement for Windows" ;;
              *)        echo "Do not recognise ${RUNNER_OS}." && exit 1 ;;
          esac
        env: 
          HOMEBREW_NO_ENV_HINTS: true
      - name: Configure Build
        run: |
          mkdir $workingDir && cd $workingDir
          case "${RUNNER_OS}" in
              Linux)    bin="/usr/bin" ;
                        tools="-DCMAKE_C_COMPILER=$bin/clang -DCMAKE_CXX_COMPILER=$bin/clang++ -DCMAKE_LINKER=$bin/ld.lld -DCMAKE_RANLIB=$bin/ranlib -DCMAKE_AR=$bin/ar" ;
                        platform="-G Ninja -DLLVM_LINK_LLVM_DYLIB=ON -DLLVM_ENABLE_LTO=Thin ${tools}" ;;
              macOS)    platform="-DCMAKE_OSX_ARCHITECTURES='x86_64;arm64' -G Ninja -DLLVM_LINK_LLVM_DYLIB=ON -DLLVM_ENABLE_LTO=Thin" ;;
              Windows)  bin="C:/Progra~1/LLVM/bin" ;
                        tools="-DCMAKE_C_COMPILER=$bin/clang-cl.exe -DCMAKE_CXX_COMPILER=$bin/clang-cl.exe -DCMAKE_LINKER=$bin/lld-link.exe -DCMAKE_RANLIB=$bin/llvm-ranlib.exe -DCMAKE_AR=$bin/llvm-ar.exe" ;
                        platform="-TClangCL -A x64 -DLLVM_BUILD_LLVM_C_DYLIB=ON -DLLVM_USE_CRT_RELEASE=MT -DLLVM_STATIC_LINK_CXX_STDLIB=ON ${tools}" ;;
              *)        echo "Do not recognise ${RUNNER_OS}." && exit 1 ;;
          esac
          cmake .. \
            -DCMAKE_INSTALL_PREFIX=_install \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_INSTALL_TOOLCHAIN_ONLY=ON \
            -DLLVM_INCLUDE_TESTS=OFF \
            -DLLVM_INCLUDE_BENCHMARKS=OFF \
            $platform
      - name: Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          msbuild /m -p:Configuration=Release INSTALL.vcxproj
        working-directory: ${{ env.workingDir }}
      - name: Posix
        if: |
          runner.os == 'macOS' ||
          runner.os == 'Linux'
        run: |
          ninja install
        working-directory: ${{ env.workingDir }}
      - name: Look for LLVM-C.DLL
        if: runner.os == 'Windows'
        run: |
          find . -name 'LLVM-c.dll'
      - name: Upload Uncompressed Binaries
        uses: actions/upload-artifact@v3
        with:
          name: LLVM-${{ runner.os }}-LTO
          path: ${{ matrix.builtAs }}
          if-no-files-found: error
      - name: Collect Files
        run: |
          mkdir $finalDir
          mv $builtAs $finalDir/$finalName
          if [[ "${RUNNER_OS}" == "Linux" ]] ; then
            chmod +x $finalDir/$finalName
          fi
          ls -la $finalDir
        env:
          builtAs: ${{ matrix.builtAs }}
          finalName: ${{ matrix.finalName }}
      - name: (skip) Split Mac Universal Binary for UPX
        if: false && runner.os == 'macOS'
        run: |
          mkdir arm64
          mkdir x64
          lipo $finalName -thin arm64 -output arm64/$finalName
          lipo $finalName -thin x86_64 -output x64/$finalName
          ls -la
        env:
          finalName: ${{ matrix.finalName }}
        working-directory: ${{ env.finalDir }}
      - name: Compress Binaries
        uses: svenstaro/upx-action@v2
        if: runner.os != 'macOS'
        with:
          file: ${{ env.finalDir }}/${{ matrix.finalName }}
          args: --best --backup
          strip: false
      - name: Validate compression
        run: |
          ls -la
        working-directory: ${{ env.finalDir }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: LLVM-${{ runner.os }}
          path: |
            ${{ env.finalDir }}/**
          if-no-files-found: error

  create-release:
    name: Create Release
    needs: [ version, build ]
    runs-on: ubuntu-latest
    #runs-on: [ self-hosted, Linux ]
    if: false
    env:
      linuxName: LLVM-Linux/${{ needs.version.outputs.linuxName }}
      macName: LLVM-macOS/${{ needs.version.outputs.macName }}
      winName: LLVM-Windows/${{ needs.version.outputs.winName }}
    steps:
      - name: Checkout Resources
        uses: actions/checkout@v3
      - name: Download Artifacts
        uses: actions/download-artifact@v4.1.7
      - name: Create NuSpec
        run: |
          text="<?xml version=\"1.0\" encoding=\"utf-8\"?>"
          text="$text\n<package xmlns=\"http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd\">"
          text="$text\n <metadata>"
          text="$text\n  <id>StirlingLabs.libLLVM</id>"
          text="$text\n  <version>$long</version>"
          text="$text\n  <title>libLLVM ${{ needs.version.outputs.short }}</title>"
          text="$text\n  <description>"
          text="$text\n    LLVM is a toolchain that can be used to develop a front end for any programming language."
          text="$text\n    This package provides LLVM libraries for convenient cross-platform use in .Net applications."
          text="$text\n  </description>"
          text="$text\n  <authors>LLVM Team, packaged by Stirling Labs</authors>"
          text="$text\n  <projectUrl>https://github.com/StirlingLabs/libLLVM</projectUrl>"
          text="$text\n  <readme>docs/README.md</readme>"
          text="$text\n  <icon>images/icon.png</icon>"
          text="$text\n  <tags>LLVM library codegen SL</tags>"
          text="$text\n  <license type=\"expression\">Apache-2.0 WITH LLVM-exception</license>"
          text="$text\n  <requireLicenseAcceptance>true</requireLicenseAcceptance>"
          text="$text\n  <repository type=\"git\" url=\"https://github.com/StirlingLabs/libLLVM.git\" branch=\"main\" commit=\"$commit\" />"
          text="$text\n </metadata>"
          text="$text\n <files>"
          text="$text\n  <file src=\"README.md\" target=\"docs/\" />"
          text="$text\n  <file src=\"icon.png\" target=\"images/\" />"
          text="$text\n  <file src=\"$linuxName\" target=\"runtimes/linux-x64/native/\" />"
          text="$text\n  <file src=\"$macName\" target=\"runtimes/osx/native/\" />"
          text="$text\n  <file src=\"$winName\" target=\"runtimes/win-x64/native/\" />"
          text="$text\n </files>"
          text="$text\n</package>"
          echo -e $text > libLLVM.nuspec
          cat libLLVM.nuspec
        env:
          commit: ${{ github.sha }}
          long: ${{ needs.version.outputs.long }}
      - name: Package Files
        run: |
          nuget pack libLLVM.nuspec
          ls -la
      - name: Upload NuPkg to GitHub 
        run: |
          dotnet nuget push *.nupkg -k ${{github.token}} -s https://nuget.pkg.github.com/${{github.repository_owner}}/index.json --no-symbols --skip-duplicate || true
          dotnet nuget push *.nupkg -k ${{secrets.NUGET_STIRLINGLABS_API_KEY}} -s https://api.nuget.org/v3/index.json --no-symbols --skip-duplicate
      - name: Create release on GitHub
        uses: softprops/action-gh-release@v0.1.14
        with:
          name: libLLVM ${{ needs.version.outputs.long }}
          files: |
            ${{ env.linuxName }}
            ${{ env.macName }}
            ${{ env.winName }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
